#!/usr/bin/env bash

sudo apt-get install git -y
sudo apt-get install python-imaging -y
sudo pip install pyBarcode

git clone https://github.com/icsfl/PaPiRus.git
cd PaPiRus
sudo python setup.py install    # Install PaPirRus python library
papirus-setup    # Install drivers and setup epaper
